<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>doc.eq.code</groupId>
        <artifactId>doc-eq-code-parent</artifactId>
        <version>1.0</version>
    </parent>

    <artifactId>dec-context-config-parse-yaml</artifactId>

    <dependencies>
        <dependency>
            <groupId>doc.eq.code</groupId>
            <artifactId>dec-core-context</artifactId>
        </dependency>
        <dependency>
            <groupId>doc.eq.code</groupId>
            <artifactId>dec-core-compiler</artifactId>
        </dependency>
        <dependency>
            <groupId>doc.eq.code</groupId>
            <artifactId>dec-core-frontends</artifactId>
        </dependency>
        <dependency>
            <groupId>org.yaml</groupId>
            <artifactId>snakeyaml</artifactId>
            <version>2.2</version>
        </dependency>
        <dependency>
            <groupId>doc.eq.code</groupId>
            <artifactId>dec-context-config-parse-xml</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-core</artifactId>
            <version>1.5.37</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.5.37</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>
