dataSourceInfo:
  default: data1
  dataSources:
    - name: data1
      type: MySQL
    - name: data2
      type: MySQL

dataFiles:
  - path: classpath:yaml/system/test-data/

viewFiles:
  - path: classpath:yaml/system/test-view/

ruleFiles:
  - path: classpath:yaml/system/test-rule/

connectionInfo:
  default: con1
  connections:
    - name: con1
      dataSources:
        - data1
    - name: con2
      dataSources:
        - data2
