package dec.core.context.runtime;

/** Stable protected-access denial algebra frozen by DESIGN-P2-R30. */
public enum DenialCode {
    POLICY_NOT_FOUND,
    POLICY_MISMATCH,
    RUNTIME_PLAN_MISMATCH,
    GUARD_UNAVAILABLE,
    CAPABILITY_ALREADY_CONSUMED,
    RUNTIME_CONTEXT_MISMATCH,
    RUNTIME_MODEL_PROVENANCE_MISMATCH,
    RUNTIME_TARGET_NOT_FOUND,
    RUNTIME_TARGET_AMBIGUOUS,
    WRITE_INTENT_NOT_FOUND,
    WRITE_INTENT_AMBIGUOUS,
    WRITE_INTENT_STALE,
    RUNTIME_SESSION_SCOPE_MISMATCH,
    RUNTIME_OBJECT_NOT_FOUND,
    RUNTIME_OBJECT_STALE,
    RUNTIME_OBJECT_ALREADY_REGISTERED,
    RUNTIME_OBJECT_OWNERSHIP_CONFLICT,
    RUNTIME_WRITE_FAILED
}
