package dec.core.context.model;

public enum DiagnosticCode {
    MIX_SOURCE_POLICY("MIX-SOURCE-POLICY"),
    MIX_SOURCE_NOT_FOUND("MIX-SOURCE-NOT-FOUND"),
    MIX_SOURCE_PATH_ESCAPE("MIX-SOURCE-PATH-ESCAPE"),
    MIX_SOURCE_DUPLICATE_ID("MIX-SOURCE-DUPLICATE-ID"),
    MIX_FRONTEND_XML_UNSAFE("MIX-FRONTEND-XML-UNSAFE"),
    MIX_FRONTEND_YAML_UNSAFE("MIX-FRONTEND-YAML-UNSAFE"),
    MIX_SYMBOL_DUPLICATE("MIX-SYMBOL-DUPLICATE"),
    MIX_REF_UNKNOWN("MIX-REF-UNKNOWN"),
    MIX_REF_RULE_SYSTEM_MISMATCH("MIX-REF-RULE-SYSTEM-MISMATCH"),
    MIX_INFORMATION_OWNER("MIX-INFORMATION-OWNER"),
    MIX_INFORMATION_CROSS_SYSTEM("MIX-INFORMATION-CROSS-SYSTEM"),
    MIX_COMMON_MEMBER("MIX-COMMON-MEMBER"),
    MIX_COMMON_UNQUALIFIED("MIX-COMMON-UNQUALIFIED"),
    MIX_REF_VIEW_NOT_DECLARED("MIX-REF-VIEW-NOT-DECLARED"),
    MIX_MODEL_ACCESS_NOT_FOUND("MIX-MODEL-ACCESS-NOT-FOUND"),
    MIX_MODEL_ACCESS_AMBIGUOUS("MIX-MODEL-ACCESS-AMBIGUOUS"),
    MIX_MODEL_ACCESS_NON_COMPOSITE("MIX-MODEL-ACCESS-NON-COMPOSITE"),
    MIX_DEFERRED_INCOMPLETE("MIX-DEFERRED-INCOMPLETE"),
    MIX_PUBLICATION_BLOCKED("MIX-PUBLICATION-BLOCKED"),
    MIX_PUBLICATION_PROVENANCE_MISMATCH("MIX-PUBLICATION-PROVENANCE-MISMATCH"),
    MIX_DIGEST_NONDETERMINISTIC("MIX-DIGEST-NONDETERMINISTIC"),
    MIX_CONTEXT_MUTATION("MIX-CONTEXT-MUTATION"),
    MIX_PROJECTION_WRITE("MIX-PROJECTION-WRITE"),
    MIX_RETIREMENT_RESIDUE("MIX-RETIREMENT-RESIDUE"),
    MIX_STRUCTURE_UNKNOWN("MIX-STRUCTURE-UNKNOWN"),
    MIX_COMPILATION_CANCELLED("MIX-COMPILATION-CANCELLED"),
    MIX_COMPILATION_TIMED_OUT("MIX-COMPILATION-TIMED-OUT"),
    MIX_CONTEXT_CONSTRUCTION_FAILED("MIX-CONTEXT-CONSTRUCTION-FAILED"),
    MIX_PUBLICATION_CONFLICT("MIX-PUBLICATION-CONFLICT"),
    MIX_PUBLICATION_FAILURE("MIX-PUBLICATION-FAILURE"),
    MIX_OBSERVER_FAILURE("MIX-OBSERVER-FAILURE");

    private final String code;

    DiagnosticCode(String code) {
        this.code = code;
    }

    public String code() {
        return code;
    }

    @Override
    public String toString() {
        return code;
    }
}
